In [35]:
'''
    클래스와 객체(Object / instance)
    
    클래스 : 복잡한 형태의 data를 메모리에 올리기 전에 
             어떤 형태인지 설명해 놓은 것(설명서)
             
             클래스 = 속성     +     기능
                      property       method
                      (멤버)변수     (멤버)메소드(함수)



    객체(Object / instance)
            : 클래스에 설명해 놓은대로
              (실행 가능한 상태로) 메모리에 올린 data
              
              객체 = 속성 + 기능
              
    객체를 생성하는 code <-- 클래스이름()
    

    학생(Student) 클래스
    이름
    나이
    주소
    학년
    키
    몸무게
'''

class Student:
    # 생성자 함수 : 클래스의 멤버변수들을 초기화함
    #   ㄴ 객체를 생성할 때 자동으로 호출되는 메소드
    def __init__(self):
        self.name = '아마존'
        self.age = 23
        self.address = '서울'
        self.grade = 3
        self.height = 187
        self.weight = 81
    # 해당 메소드 실행 시 self로 인해서 어떤 student 객체인지 판별할 수 있음. 객체 주소를 담음 
    def display_info(self):
        print(f'''이름 : {self.name}
나이 : {self.age}
주소 : {self.address}
학년 : {self.grade}
키   : {self.height}
체중 : {self.weight}''')
        
    
'''
Student 객체를 생성하는 명령(code) <-- Student()
    ㄴ 클래스에 설명한대로 data를 메모리에 올리라는 명령
                            ㄴ 멤버변수
init 함수에 있는 데이터가 같은 주소지에 올라감
'''
# 생성자를 호출하는 코드
Student()
student1 = Student()
print(student1.name)
print(student1.age)
print(student1.address)
print(student1.grade)
print(student1.height)
print(student1.weight)

'''
student1 이 저장하고 있는 주소지에 있는
data로 display_info() 메소드를 호출함(실행시킴)
'''

student1.display_info()

student2 = Student()
print(student2.name)
print(student2.age)
print(student2.address)
print(student2.grade)
print(student2.height)
print(student2.weight)

student2.name = '이순신'
print('student1.name :', student1.name)
print('student2.name :', student2.name)

student1.name = '강감찬'
print('student1.name :', student1.name)
print('student2.name :', student2.name)


student2.age = 72
student2.address ='강남'
student2.grade = 2
student2.height = 179
student2.weight = 75

'''
student2 이 저장하고 있는 주소지에 있는
data로 display_info() 메소드를 호출함(실행시킴)
'''
student2.display_info()

아마존
23
서울
3
187
81
이름 : 아마존
나이 : 23
주소 : 서울
학년 : 3
키   : 187
체중 : 81
아마존
23
서울
3
187
81
student1.name : 아마존
student2.name : 이순신
student1.name : 강감찬
student2.name : 이순신
이름 : 이순신
나이 : 72
주소 : 강남
학년 : 2
키   : 179
체중 : 75

In [34]:
print('-- student1 주소지의 정보로 display_info() 호출함 --')
student1.display_info()

print('-- student2 주소지의 정보로 display_info() 호출함 --')
student2.display_info()

-- student1 주소지의 정보로 display_info() 호출함 --
이름 : 강감찬
나이 : 23
주소 : 서울
학년 : 3
키   : 187
체중 : 81
-- student2 주소지의 정보로 display_info() 호출함 --
이름 : 이순신
나이 : 72
주소 : 강남
학년 : 2
키   : 179
체중 : 75

In [48]:
class Person:
    
    # 생성자 함수 : 클래스의 멤버변수들을 초기화함
    #   ㄴ 객체를 생성할 때 자동으로 호출되는 메소드
    def __init__(self, name, age, addr, grade):
        self.name = name
        self.age = age
        self.addr = addr
        self.grade = grade
    
    def work(self):
        print(f'{self.name} 은(는) 열심히 일합니다')
    
    def gotowork(self):
        print(f'{self.name} 은(는) 직장에 출근합니다')
        
    def introduce(self):
        print(f'''이름 : {self.name}
나이 : {self.age}
주소 : {self.addr}
등급 : {self.grade}''')
    
    
person1 = Person('장보고', 32, '청해진', 1)
print('person1.name :', person1.name)
print('person1.age :', person1.age)
print('person1.addr :', person1.addr)
print('person1.grade :', person1.grade)

person2 = Person('안중근', 30, '황해도', 2)
print('person2.name :', person2.name)
print('person2.age :', person2.age)
print('person2.addr :', person2.addr)
print('person2.grade :', person2.grade)

print('-' * 60)
person2.work()
person2.gotowork()
person2.introduce()

person1.name : 장보고
person1.age : 32
person1.addr : 청해진
person1.grade : 1
person2.name : 안중근
person2.age : 30
person2.addr : 황해도
person2.grade : 2
------------------------------------------------------------
안중근 은(는) 열심히 일합니다
안중근 은(는) 직장에 출근합니다
이름 : 안중근
나이 : 30
주소 : 황해도
등급 : 2